In [1]:
import sys
sys.path.append('/Users/pschulam/Git/mypy')
sys.path.append('/Users/pschulam/Git/nips15-model')

In [257]:
import numpy as np
import dataprep
import multipsm
import owlqn
from scipy.misc import logsumexp

In [276]:
import imp
import logging
from mypy.util import check_grad
imp.reload(logging)
imp.reload(multipsm)
logging.basicConfig(level=logging.INFO)

In [3]:
fold = 1
models = dataprep.get_models(fold)
col_names = dataprep.col_names
censor_time = 30.0
train_data, test_data = dataprep.get_train_test(fold, models, col_names, censor_time)

In [211]:
examples = [X for X, _ in train_data]

In [277]:
prior = multipsm.MultiPSMPrior([8, 4, 6, 4], [5, 3, 3, 3])

In [278]:
loglik_1 = multipsm.MultiPSMLikelihood(8, 2, -1, 25, 2, 6, 16.0, 36.0, 2.0, 1.0)
loglik_2 = multipsm.MultiPSMLikelihood(4, 2, -1, 25, 2, 6,  9.0, 16.0, 2.0, 1.0)
loglik_3 = multipsm.MultiPSMLikelihood(6, 2, -1, 25, 2, 6, 16.0, 36.0, 2.0, 1.0)
loglik_4 = multipsm.MultiPSMLikelihood(4, 2, -1, 25, 2, 6, 25.0, 16.0, 2.0, 1.0)

In [279]:
model = multipsm.MultiPSM(prior, [loglik_1, loglik_2, loglik_3, loglik_4])

In [280]:
model.fit(examples)

INFO:root:Prior objective evaluated: 6.356245, ||w||_0: 194
INFO:root:Prior objective evaluated: 5.522835, ||w||_0: 191
INFO:root:Prior objective evaluated: 5.091736, ||w||_0: 186
INFO:root:Prior objective evaluated: 4.943954, ||w||_0: 192
INFO:root:Prior objective evaluated: 4.799909, ||w||_0: 189
INFO:root:Prior objective evaluated: 4.638179, ||w||_0: 191
INFO:root:Prior objective evaluated: 4.513469, ||w||_0: 182
INFO:root:Prior objective evaluated: 4.453334, ||w||_0: 188
INFO:root:Prior objective evaluated: 4.427788, ||w||_0: 192
INFO:root:Prior objective evaluated: 4.415782, ||w||_0: 192
INFO:root:Prior objective evaluated: 4.395303, ||w||_0: 186
INFO:root:Prior objective evaluated: 4.385462, ||w||_0: 185
INFO:root:Prior objective evaluated: 4.366230, ||w||_0: 188
INFO:root:Prior objective evaluated: 4.362724, ||w||_0: 191
INFO:root:Prior objective evaluated: 4.356520, ||w||_0: 189
INFO:root:Prior objective evaluated: 4.356247, ||w||_0: 185
INFO:root:Prior objective evaluated: 4.3

In [254]:
prior_obj(w0)

6.356245172264539

In [255]:
check_grad(prior_obj, w0, range(3))[:3]

array([ 0.28014657,  0.21888154,  0.00479137])

In [256]:
prior_jac(w0)[:3]

array([ 0.28014601,  0.21888108,  0.00479129])

In [218]:
check_grad(prior_obj, w0, range(3))[:3]

array([-0.18678543, -0.13715171, -0.07640919])

In [75]:
logsumexp(all_pair[0][0], axis=0)

array([-0.96465177, -0.96516055, -1.43907483, -7.11230901])

In [40]:
loglik = model.fit(examples)

In [46]:
loglik[3].shape

(597, 4)

In [16]:
parameters = model.fit(examples)

In [22]:
x, f, _, y = examples[0][0]

In [23]:
loglik_1.log_proba(x, f, y, *parameters[0])

array([-54.21733056, -47.19413548, -43.60407956, -41.70210928,
       -41.26428083, -42.23867108, -44.83805506, -50.14918997])

In [67]:
model.fit([8, 4, 6, 4], examples)

In [51]:
covariance_fn = multipsm.Kernel()

In [52]:
pop_factor = multipsm.LinearRegressionFactor(2, covariance_fn)

In [53]:
subpop_factor = multipsm.BSplineFactor(-1, 25, 2, 6, covariance_fn)

In [54]:
pop_factor.num_features

2

In [55]:
subpop_factor.num_features

6

In [56]:
train_data[0]

([(array([  0.0492813,   1.17454  ,   2.28337  ,   3.72348  ,   4.81588  ,
            5.59617  ,   6.69131  ,   7.82478  ,   8.82136  ,   9.85626  ,
           10.8172   ,  11.8275   ,  12.9035   ,  13.8973   ]),
   array([1, 0]),
   array([ 1.,  1.,  0.,  0.,  0.]),
   array([ 87.89,  83.18,  74.38,  82.02,  74.84,  69.09,  71.11,  71.66,
           74.05,  70.57,  73.4 ,  76.27,  77.13,  76.14])),
  (array([  0.     ,   3.33973,   3.70685,   4.2    ,   4.87671,   5.58082,
            6.04658,   6.71233,   7.34521,   7.83014,   8.32603,   8.8274 ,
            9.32603,   9.82192,  10.5342 ,  11.8356 ,  12.9123 ,  13.4274 ,
           13.9068 ,  14.4082 ]),
   array([1, 0]),
   array([ 1.,  1.,  0.]),
   array([ 2.,  2.,  7.,  3.,  4.,  7.,  2.,  4.,  2.,  2.,  4.,  3.,  5.,
           5.,  0.,  0.,  2.,  0.,  2.,  2.])),
  (array([  0.0493151,   1.17534  ,   2.28493  ,   3.72603  ,   4.81918  ,
            5.6      ,   6.69589  ,   7.83014  ,   8.8274   ,   9.86301  ,
           10.82